# Generated by Django 4.2 on 2023-05-07 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_category_product_created_data_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pd_stoct',
            new_name='pd_stock',
        ),
    ]
