# Generated by Django 4.2 on 2023-05-15 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_brand_product_brand_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand_image',
        ),
    ]
