# Generated by Django 4.2 on 2023-05-21 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_productgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'product gallery'},
        ),
    ]
