# Generated by Django 4.2 on 2023-05-31 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_productspec_productdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.SlugField(max_length=150, null=True, unique=True),
        ),
    ]
