# Generated by Django 4.2 on 2023-05-21 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_action_actioncontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactlist',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
